use std::process::ExitCode;
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{anyhow, bail, Context, Result};
use clap::{Parser, ValueEnum};
use mini_aec_sender::{ValidationSignal, FRAMES_PER_SECOND};
use mini_aec_transport::{
  PcmFormat, PcmFrame, SessionConfig, SessionId, SessionState, SinkDiagnostics, SinkError,
  SinkErrorKind, VirtualMicrophoneSink, WriteReceipt,
};
use serde::Serialize;

#[derive(Debug, Parser)]
#[command(name = "mini-aec-sender")]
#[command(about = "Send deterministic PCM to a MiniAEC virtual microphone transport")]
struct Cli {
  /// Number of seconds to send; five minutes is the candidate comparison duration.
  #[arg(long, default_value_t = 5)]
  duration_seconds: u64,

  /// Optional nonzero decimal u128 session identity. A process-unique value is generated by default.
  #[arg(long)]
  session_id: Option<u128>,

  /// Adapter to open. Driver candidates are added here after their isolated implementations exist.
  #[arg(long, value_enum, default_value_t = Transport::DryRun)]
  transport: Transport,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum Transport {
  /// Validate generation, pacing and logs without writing audio to a driver.
  DryRun,
}

#[derive(Debug, Serialize)]
#[serde(tag = "event", rename_all = "snake_case")]
enum SenderEvent {
  SessionOpened {
    session_id: String,
    sample_rate_hz: u32,
    channels: u16,
    bits_per_sample: u16,
    frame_samples: u16,
  },
  FrameAccepted {
    session_id: String,
    sequence: u64,
    marker_active: bool,
  },
  Diagnostics {
    session_id: String,
    schema_version: u16,
    accepted_frames: u64,
    rejected_writes: u64,
    underruns: u64,
    overflows: u64,
    driver_restarts: u64,
  },
  SessionClosed {
    session_id: String,
    frames_sent: u64,
  },
}

fn main() -> ExitCode {
  match run() {
    Ok(()) => ExitCode::SUCCESS,
    Err(error) => {
      eprintln!("mini-aec-sender failed: {error:#}");
      ExitCode::FAILURE
    }
  }
}

fn run() -> Result<()> {
  let cli = Cli::parse();
  if cli.duration_seconds == 0 {
    bail!("--duration-seconds must be greater than zero");
  }

  let session_id = match cli.session_id {
    Some(value) => SessionId::new(value).ok_or_else(|| anyhow!("--session-id must be nonzero"))?,
    None => generated_session_id()?,
  };
  let total_frames = cli
    .duration_seconds
    .checked_mul(FRAMES_PER_SECOND)
    .context("requested duration is too large")?;

  match cli.transport {
    Transport::DryRun => send(&mut DryRunSink::default(), session_id, total_frames),
  }
}

fn send(
  sink: &mut dyn VirtualMicrophoneSink,
  session_id: SessionId,
  total_frames: u64,
) -> Result<()> {
  let session = SessionConfig::new(session_id);
  sink
    .open_session(session)
    .context("failed to open virtual microphone session")?;
  emit(&SenderEvent::SessionOpened {
    session_id: format_session_id(session_id),
    sample_rate_hz: session.format().sample_rate_hz(),
    channels: session.format().channels(),
    bits_per_sample: session.format().bits_per_sample(),
    frame_samples: session.format().frame_samples_per_channel(),
  })?;

  let mut signal = ValidationSignal::new(session_id);
  let start = Instant::now();
  let send_result = (|| -> Result<()> {
    for expected_sequence in 0..total_frames {
      let deadline = start + Duration::from_millis(expected_sequence.saturating_mul(10));
      if let Some(delay) = deadline.checked_duration_since(Instant::now()) {
        thread::sleep(delay);
      }

      let frame = signal.next_frame();
      let receipt = sink
        .write_frame(frame.as_pcm_frame())
        .with_context(|| format!("transport rejected frame {expected_sequence}"))?;
      if receipt.sequence() != expected_sequence {
        bail!(
          "transport acknowledged sequence {} for submitted frame {expected_sequence}",
          receipt.sequence()
        );
      }
      emit(&SenderEvent::FrameAccepted {
        session_id: format_session_id(frame.session_id()),
        sequence: frame.sequence(),
        marker_active: frame.marker_active(),
      })?;
    }
    Ok(())
  })();

  let diagnostics_result = sink.diagnostics();
  let close_result = sink.close_session();
  send_result?;
  let diagnostics = diagnostics_result.context("failed to read transport diagnostics")?;
  close_result.context("failed to close virtual microphone session")?;

  emit(&SenderEvent::Diagnostics {
    session_id: format_session_id(session_id),
    schema_version: diagnostics.schema_version,
    accepted_frames: diagnostics.counters.accepted_frames,
    rejected_writes: diagnostics.counters.rejected_writes,
    underruns: diagnostics.counters.underruns,
    overflows: diagnostics.counters.overflows,
    driver_restarts: diagnostics.counters.driver_restarts,
  })?;
  emit(&SenderEvent::SessionClosed {
    session_id: format_session_id(session_id),
    frames_sent: total_frames,
  })
}

fn generated_session_id() -> Result<SessionId> {
  let timestamp = SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .context("system clock is before the Unix epoch")?
    .as_nanos();
  let process_component = u128::from(std::process::id()) << 96;
  SessionId::new(timestamp ^ process_component)
    .ok_or_else(|| anyhow!("generated the reserved zero session identity"))
}

fn format_session_id(session_id: SessionId) -> String {
  format!("{:032x}", session_id.get())
}

fn emit(event: &SenderEvent) -> Result<()> {
  println!("{}", serde_json::to_string(event)?);
  Ok(())
}

#[derive(Debug, Default)]
struct DryRunSink {
  diagnostics: SinkDiagnostics,
}

impl VirtualMicrophoneSink for DryRunSink {
  fn open_session(&mut self, config: SessionConfig) -> Result<(), SinkError> {
    if self.diagnostics.state == SessionState::Open {
      return Err(SinkError::new(
        SinkErrorKind::InvalidState,
        "a dry-run session is already open",
      ));
    }
    if config.format() != PcmFormat::MONO_48_KHZ_PCM16 {
      return Err(SinkError::new(
        SinkErrorKind::InvalidFormat,
        "the dry-run adapter accepts only the MiniAEC fixed PCM format",
      ));
    }
    self.diagnostics.state = SessionState::Open;
    self.diagnostics.active_session = Some(config.session_id());
    self.diagnostics.last_accepted_sequence = None;
    self.diagnostics.counters.session_opens += 1;
    Ok(())
  }

  fn write_frame(&mut self, frame: PcmFrame<'_>) -> Result<WriteReceipt, SinkError> {
    if self.diagnostics.state != SessionState::Open {
      self.diagnostics.counters.rejected_writes += 1;
      return Err(SinkError::new(
        SinkErrorKind::InvalidState,
        "no dry-run session is open",
      ));
    }
    let expected = self
      .diagnostics
      .last_accepted_sequence
      .map_or(0, |sequence| sequence.wrapping_add(1));
    if frame.sequence() != expected {
      self.diagnostics.counters.rejected_writes += 1;
      return Err(SinkError::new(
        SinkErrorKind::SequenceViolation,
        format!("expected frame {expected}, received {}", frame.sequence()),
      ));
    }
    self.diagnostics.last_accepted_sequence = Some(frame.sequence());
    self.diagnostics.counters.accepted_frames += 1;
    Ok(WriteReceipt::accepted(frame.sequence()))
  }

  fn diagnostics(&self) -> Result<SinkDiagnostics, SinkError> {
    Ok(self.diagnostics)
  }

  fn close_session(&mut self) -> Result<(), SinkError> {
    if self.diagnostics.state == SessionState::Open {
      self.diagnostics.state = SessionState::Closed;
      self.diagnostics.active_session = None;
      self.diagnostics.counters.session_closes += 1;
    }
    Ok(())
  }
}

#[cfg(test)]
mod tests {
  use mini_aec_transport::{
    PcmFrame, SessionConfig, SessionId, SinkErrorKind, VirtualMicrophoneSink, FRAME_SAMPLES,
  };

  use super::DryRunSink;

  fn session(value: u128) -> SessionId {
    SessionId::new(value).expect("test session is nonzero")
  }

  #[test]
  fn dry_run_maps_invalid_state_and_sequence_errors() {
    let samples = [0_i16; FRAME_SAMPLES];
    let mut sink = DryRunSink::default();

    let error = sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect_err("write without a session must fail");
    assert_eq!(error.kind(), SinkErrorKind::InvalidState);

    sink
      .open_session(SessionConfig::new(session(1)))
      .expect("first session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("first frame is accepted");
    let error = sink
      .write_frame(PcmFrame::new(2, &samples))
      .expect_err("skipped sequence must fail");
    assert_eq!(error.kind(), SinkErrorKind::SequenceViolation);

    let diagnostics = sink.diagnostics().expect("diagnostics are available");
    assert_eq!(diagnostics.counters.accepted_frames, 1);
    assert_eq!(diagnostics.counters.rejected_writes, 2);
  }

  #[test]
  fn dry_run_clears_sequence_state_for_a_new_session() {
    let samples = [0_i16; FRAME_SAMPLES];
    let mut sink = DryRunSink::default();
    sink
      .open_session(SessionConfig::new(session(1)))
      .expect("first session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("first frame is accepted");
    sink.close_session().expect("first session closes");

    sink
      .open_session(SessionConfig::new(session(2)))
      .expect("second session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("second session restarts at zero");

    let diagnostics = sink.diagnostics().expect("diagnostics are available");
    assert_eq!(diagnostics.active_session, Some(session(2)));
    assert_eq!(diagnostics.last_accepted_sequence, Some(0));
    assert_eq!(diagnostics.counters.session_opens, 2);
    assert_eq!(diagnostics.counters.session_closes, 1);
  }
}
