use std::process::ExitCode;
use std::thread;
use std::time::{Duration, Instant, SystemTime, UNIX_EPOCH};

use anyhow::{anyhow, bail, Context, Result};
use clap::{Parser, ValueEnum};
use mini_aec_sender::{ValidationSignal, FRAMES_PER_SECOND};
use mini_aec_transport::{
  PcmFormat, PcmFrame, SessionConfig, SessionId, SessionState, SinkDiagnostics, SinkError,
  SinkErrorKind, VirtualMicrophoneSink, WriteReceipt,
};
use mini_aec_windows_transport::WindowsVirtualMicrophoneSink;
use serde::Serialize;

const FRAME_DURATION_MILLIS: u64 = 10;
const STARTUP_PREFILL_FRAMES: u64 = 3;
const DRAIN_TIMEOUT: Duration = Duration::from_secs(1);
const DRAIN_POLL_INTERVAL: Duration = Duration::from_millis(2);

#[derive(Debug, Parser)]
#[command(name = "mini-aec-sender")]
#[command(about = "Send deterministic PCM to a MiniAEC virtual microphone transport")]
struct Cli {
  /// Number of seconds to send; five minutes is the candidate comparison duration.
  #[arg(long, default_value_t = 5)]
  duration_seconds: u64,

  /// Open one session, write one frame, read diagnostics and close without waiting for capture drain.
  #[arg(long)]
  access_probe: bool,

  /// Keep an access-probe handle open for contention validation before closing it.
  #[arg(long, default_value_t = 0, requires = "access_probe")]
  hold_seconds: u64,

  /// Optional nonzero decimal u128 session identity. A process-unique value is generated by default.
  #[arg(long)]
  session_id: Option<u128>,

  /// Adapter to open.
  #[arg(long, value_enum, default_value_t = Transport::DryRun)]
  transport: Transport,
}

#[derive(Clone, Copy, Debug, ValueEnum)]
enum Transport {
  /// Send frames to the installed `MiniAEC` validation driver.
  Driver,

  /// Validate generation, pacing and logs without writing audio to a driver.
  DryRun,
}

#[derive(Debug, Serialize)]
#[serde(tag = "event", rename_all = "snake_case")]
enum SenderEvent {
  SessionOpened {
    session_id: String,
    sample_rate_hz: u32,
    channels: u16,
    bits_per_sample: u16,
    frame_samples: u16,
  },
  FrameAccepted {
    session_id: String,
    sequence: u64,
    marker_active: bool,
  },
  Diagnostics {
    session_id: String,
    #[serde(flatten)]
    diagnostics: Box<DiagnosticsEvent>,
  },
  SessionClosed {
    session_id: String,
    frames_sent: u64,
  },
}

#[derive(Debug, Serialize)]
struct DiagnosticsEvent {
  baseline: DiagnosticsSnapshotEvent,
  before_close: DiagnosticsSnapshotEvent,
  after_close: DiagnosticsSnapshotEvent,
  delta: DiagnosticCountersEvent,
  drain_wait_milliseconds: u128,
}

#[derive(Debug, Serialize)]
struct DiagnosticsSnapshotEvent {
  schema_version: u16,
  state: &'static str,
  active_session: Option<String>,
  last_accepted_sequence: Option<u64>,
  current_depth: u32,
  high_water_mark: u32,
  counters: DiagnosticCountersEvent,
}

#[derive(Debug, Serialize)]
struct DiagnosticCountersEvent {
  session_opens: u64,
  session_closes: u64,
  session_resets: u64,
  accepted_frames: u64,
  rejected_writes: u64,
  underruns: u64,
  overflows: u64,
  discarded_frames: u64,
  driver_restarts: u64,
}

fn main() -> ExitCode {
  match run() {
    Ok(()) => ExitCode::SUCCESS,
    Err(error) => {
      eprintln!("mini-aec-sender failed: {error:#}");
      ExitCode::FAILURE
    }
  }
}

fn run() -> Result<()> {
  let cli = Cli::parse();
  if !cli.access_probe && cli.duration_seconds == 0 {
    bail!("--duration-seconds must be greater than zero");
  }

  let session_id = match cli.session_id {
    Some(value) => SessionId::new(value).ok_or_else(|| anyhow!("--session-id must be nonzero"))?,
    None => generated_session_id()?,
  };
  let total_frames = cli
    .duration_seconds
    .checked_mul(FRAMES_PER_SECOND)
    .context("requested duration is too large")?;

  match cli.transport {
    Transport::Driver => {
      let mut sink = WindowsVirtualMicrophoneSink::connect()
        .context("failed to connect to the MiniAEC validation driver")?;
      run_with_sink(
        &mut sink,
        session_id,
        total_frames,
        cli.access_probe,
        cli.hold_seconds,
      )
    }
    Transport::DryRun => run_with_sink(
      &mut DryRunSink::default(),
      session_id,
      total_frames,
      cli.access_probe,
      cli.hold_seconds,
    ),
  }
}

fn run_with_sink(
  sink: &mut dyn VirtualMicrophoneSink,
  session_id: SessionId,
  total_frames: u64,
  access_probe: bool,
  hold_seconds: u64,
) -> Result<()> {
  if access_probe {
    probe_access(sink, session_id, Duration::from_secs(hold_seconds))
  } else {
    send(sink, session_id, total_frames)
  }
}

fn probe_access(
  sink: &mut dyn VirtualMicrophoneSink,
  session_id: SessionId,
  hold_duration: Duration,
) -> Result<()> {
  let baseline = sink
    .diagnostics()
    .context("failed to read baseline transport diagnostics")?;
  let session = SessionConfig::new(session_id);
  sink
    .open_session(session)
    .context("failed to open virtual microphone session")?;
  emit(&SenderEvent::SessionOpened {
    session_id: format_session_id(session_id),
    sample_rate_hz: session.format().sample_rate_hz(),
    channels: session.format().channels(),
    bits_per_sample: session.format().bits_per_sample(),
    frame_samples: session.format().frame_samples_per_channel(),
  })?;

  let probe_result = (|| -> Result<()> {
    let mut signal = ValidationSignal::new(session_id);
    let frame = signal.next_frame();
    let receipt = sink
      .write_frame(frame.as_pcm_frame())
      .context("transport rejected access-probe frame")?;
    if receipt.sequence() != 0 {
      bail!(
        "transport acknowledged sequence {} for access-probe frame zero",
        receipt.sequence()
      );
    }
    emit(&SenderEvent::FrameAccepted {
      session_id: format_session_id(frame.session_id()),
      sequence: frame.sequence(),
      marker_active: frame.marker_active(),
    })?;
    if !hold_duration.is_zero() {
      thread::sleep(hold_duration);
    }
    Ok(())
  })();

  let before_close_result = sink.diagnostics();
  let close_result = sink.close_session();
  let after_close_result = sink.diagnostics();
  probe_result?;
  let before_close = before_close_result.context("failed to read probe diagnostics")?;
  close_result.context("failed to close access-probe session")?;
  let after_close = after_close_result.context("failed to read final transport diagnostics")?;
  emit_diagnostics(
    session_id,
    &baseline,
    &before_close,
    &after_close,
    Duration::ZERO,
  )?;
  emit(&SenderEvent::SessionClosed {
    session_id: format_session_id(session_id),
    frames_sent: 1,
  })
}

fn send(
  sink: &mut dyn VirtualMicrophoneSink,
  session_id: SessionId,
  total_frames: u64,
) -> Result<()> {
  let baseline = sink
    .diagnostics()
    .context("failed to read baseline transport diagnostics")?;
  let session = SessionConfig::new(session_id);
  sink
    .open_session(session)
    .context("failed to open virtual microphone session")?;
  emit(&SenderEvent::SessionOpened {
    session_id: format_session_id(session_id),
    sample_rate_hz: session.format().sample_rate_hz(),
    channels: session.format().channels(),
    bits_per_sample: session.format().bits_per_sample(),
    frame_samples: session.format().frame_samples_per_channel(),
  })?;

  let mut signal = ValidationSignal::new(session_id);
  let start = Instant::now();
  let send_result = (|| -> Result<()> {
    for expected_sequence in 0..total_frames {
      let paced_sequence =
        expected_sequence.saturating_sub(STARTUP_PREFILL_FRAMES.saturating_sub(1));
      let deadline =
        start + Duration::from_millis(paced_sequence.saturating_mul(FRAME_DURATION_MILLIS));
      if let Some(delay) = deadline.checked_duration_since(Instant::now()) {
        thread::sleep(delay);
      }

      let frame = signal.next_frame();
      let receipt = sink
        .write_frame(frame.as_pcm_frame())
        .with_context(|| format!("transport rejected frame {expected_sequence}"))?;
      if receipt.sequence() != expected_sequence {
        bail!(
          "transport acknowledged sequence {} for submitted frame {expected_sequence}",
          receipt.sequence()
        );
      }
      emit(&SenderEvent::FrameAccepted {
        session_id: format_session_id(frame.session_id()),
        sequence: frame.sequence(),
        marker_active: frame.marker_active(),
      })?;
    }
    Ok(())
  })();

  let drain_result = if send_result.is_ok() {
    wait_for_drain(sink)
  } else {
    sink
      .diagnostics()
      .map(|diagnostics| (diagnostics, Duration::ZERO))
  };
  let close_result = sink.close_session();
  let after_close_result = sink.diagnostics();
  send_result?;
  let (before_close, drain_wait) =
    drain_result.context("failed to drain the virtual microphone transport")?;
  close_result.context("failed to close virtual microphone session")?;
  let after_close = after_close_result.context("failed to read final transport diagnostics")?;

  emit_diagnostics(
    session_id,
    &baseline,
    &before_close,
    &after_close,
    drain_wait,
  )?;
  emit(&SenderEvent::SessionClosed {
    session_id: format_session_id(session_id),
    frames_sent: total_frames,
  })
}

fn emit_diagnostics(
  session_id: SessionId,
  baseline: &SinkDiagnostics,
  before_close: &SinkDiagnostics,
  after_close: &SinkDiagnostics,
  drain_wait: Duration,
) -> Result<()> {
  emit(&SenderEvent::Diagnostics {
    session_id: format_session_id(session_id),
    diagnostics: Box::new(DiagnosticsEvent {
      baseline: diagnostics_snapshot_event(baseline),
      before_close: diagnostics_snapshot_event(before_close),
      after_close: diagnostics_snapshot_event(after_close),
      delta: diagnostic_counter_delta(after_close, baseline),
      drain_wait_milliseconds: drain_wait.as_millis(),
    }),
  })
}

fn wait_for_drain(
  sink: &dyn VirtualMicrophoneSink,
) -> Result<(SinkDiagnostics, Duration), SinkError> {
  let start = Instant::now();
  loop {
    let diagnostics = sink.diagnostics()?;
    if diagnostics.current_depth == 0 {
      return Ok((diagnostics, start.elapsed()));
    }
    if start.elapsed() >= DRAIN_TIMEOUT {
      return Err(SinkError::new(
        SinkErrorKind::TransportFailure,
        format!(
          "transport still holds {} frame(s) after {} ms",
          diagnostics.current_depth,
          DRAIN_TIMEOUT.as_millis()
        ),
      ));
    }
    thread::sleep(DRAIN_POLL_INTERVAL);
  }
}

fn diagnostics_snapshot_event(diagnostics: &SinkDiagnostics) -> DiagnosticsSnapshotEvent {
  DiagnosticsSnapshotEvent {
    schema_version: diagnostics.schema_version,
    state: match diagnostics.state {
      SessionState::Closed => "closed",
      SessionState::Open => "open",
    },
    active_session: diagnostics.active_session.map(format_session_id),
    last_accepted_sequence: diagnostics.last_accepted_sequence,
    current_depth: diagnostics.current_depth,
    high_water_mark: diagnostics.high_water_mark,
    counters: diagnostic_counters_event(diagnostics),
  }
}

fn diagnostic_counters_event(diagnostics: &SinkDiagnostics) -> DiagnosticCountersEvent {
  let counters = diagnostics.counters;
  DiagnosticCountersEvent {
    session_opens: counters.session_opens,
    session_closes: counters.session_closes,
    session_resets: counters.session_resets,
    accepted_frames: counters.accepted_frames,
    rejected_writes: counters.rejected_writes,
    underruns: counters.underruns,
    overflows: counters.overflows,
    discarded_frames: counters.discarded_frames,
    driver_restarts: counters.driver_restarts,
  }
}

fn diagnostic_counter_delta(
  current: &SinkDiagnostics,
  baseline: &SinkDiagnostics,
) -> DiagnosticCountersEvent {
  let current = current.counters;
  let baseline = baseline.counters;
  DiagnosticCountersEvent {
    session_opens: current.session_opens.saturating_sub(baseline.session_opens),
    session_closes: current
      .session_closes
      .saturating_sub(baseline.session_closes),
    session_resets: current
      .session_resets
      .saturating_sub(baseline.session_resets),
    accepted_frames: current
      .accepted_frames
      .saturating_sub(baseline.accepted_frames),
    rejected_writes: current
      .rejected_writes
      .saturating_sub(baseline.rejected_writes),
    underruns: current.underruns.saturating_sub(baseline.underruns),
    overflows: current.overflows.saturating_sub(baseline.overflows),
    discarded_frames: current
      .discarded_frames
      .saturating_sub(baseline.discarded_frames),
    driver_restarts: current
      .driver_restarts
      .saturating_sub(baseline.driver_restarts),
  }
}

fn generated_session_id() -> Result<SessionId> {
  let timestamp = SystemTime::now()
    .duration_since(UNIX_EPOCH)
    .context("system clock is before the Unix epoch")?
    .as_nanos();
  let process_component = u128::from(std::process::id()) << 96;
  SessionId::new(timestamp ^ process_component)
    .ok_or_else(|| anyhow!("generated the reserved zero session identity"))
}

fn format_session_id(session_id: SessionId) -> String {
  format!("{:032x}", session_id.get())
}

fn emit(event: &SenderEvent) -> Result<()> {
  println!("{}", serde_json::to_string(event)?);
  Ok(())
}

#[derive(Debug, Default)]
struct DryRunSink {
  diagnostics: SinkDiagnostics,
}

impl VirtualMicrophoneSink for DryRunSink {
  fn open_session(&mut self, config: SessionConfig) -> Result<(), SinkError> {
    if self.diagnostics.state == SessionState::Open {
      return Err(SinkError::new(
        SinkErrorKind::InvalidState,
        "a dry-run session is already open",
      ));
    }
    if config.format() != PcmFormat::MONO_48_KHZ_PCM16 {
      return Err(SinkError::new(
        SinkErrorKind::InvalidFormat,
        "the dry-run adapter accepts only the MiniAEC fixed PCM format",
      ));
    }
    self.diagnostics.state = SessionState::Open;
    self.diagnostics.active_session = Some(config.session_id());
    self.diagnostics.last_accepted_sequence = None;
    self.diagnostics.counters.session_opens += 1;
    Ok(())
  }

  fn write_frame(&mut self, frame: PcmFrame<'_>) -> Result<WriteReceipt, SinkError> {
    if self.diagnostics.state != SessionState::Open {
      self.diagnostics.counters.rejected_writes += 1;
      return Err(SinkError::new(
        SinkErrorKind::InvalidState,
        "no dry-run session is open",
      ));
    }
    let expected = self
      .diagnostics
      .last_accepted_sequence
      .map_or(0, |sequence| sequence.wrapping_add(1));
    if frame.sequence() != expected {
      self.diagnostics.counters.rejected_writes += 1;
      return Err(SinkError::new(
        SinkErrorKind::SequenceViolation,
        format!("expected frame {expected}, received {}", frame.sequence()),
      ));
    }
    self.diagnostics.last_accepted_sequence = Some(frame.sequence());
    self.diagnostics.counters.accepted_frames += 1;
    Ok(WriteReceipt::accepted(frame.sequence()))
  }

  fn diagnostics(&self) -> Result<SinkDiagnostics, SinkError> {
    Ok(self.diagnostics)
  }

  fn close_session(&mut self) -> Result<(), SinkError> {
    if self.diagnostics.state == SessionState::Open {
      self.diagnostics.state = SessionState::Closed;
      self.diagnostics.active_session = None;
      self.diagnostics.counters.session_closes += 1;
    }
    Ok(())
  }
}

#[cfg(test)]
mod tests {
  use clap::Parser;
  use mini_aec_transport::{
    PcmFrame, SessionConfig, SessionId, SinkErrorKind, VirtualMicrophoneSink, FRAME_SAMPLES,
  };

  use super::{Cli, DryRunSink};

  fn session(value: u128) -> SessionId {
    SessionId::new(value).expect("test session is nonzero")
  }

  #[test]
  fn dry_run_maps_invalid_state_and_sequence_errors() {
    let samples = [0_i16; FRAME_SAMPLES];
    let mut sink = DryRunSink::default();

    let error = sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect_err("write without a session must fail");
    assert_eq!(error.kind(), SinkErrorKind::InvalidState);

    sink
      .open_session(SessionConfig::new(session(1)))
      .expect("first session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("first frame is accepted");
    let error = sink
      .write_frame(PcmFrame::new(2, &samples))
      .expect_err("skipped sequence must fail");
    assert_eq!(error.kind(), SinkErrorKind::SequenceViolation);

    let diagnostics = sink.diagnostics().expect("diagnostics are available");
    assert_eq!(diagnostics.counters.accepted_frames, 1);
    assert_eq!(diagnostics.counters.rejected_writes, 2);
  }

  #[test]
  fn dry_run_clears_sequence_state_for_a_new_session() {
    let samples = [0_i16; FRAME_SAMPLES];
    let mut sink = DryRunSink::default();
    sink
      .open_session(SessionConfig::new(session(1)))
      .expect("first session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("first frame is accepted");
    sink.close_session().expect("first session closes");

    sink
      .open_session(SessionConfig::new(session(2)))
      .expect("second session opens");
    sink
      .write_frame(PcmFrame::new(0, &samples))
      .expect("second session restarts at zero");

    let diagnostics = sink.diagnostics().expect("diagnostics are available");
    assert_eq!(diagnostics.active_session, Some(session(2)));
    assert_eq!(diagnostics.last_accepted_sequence, Some(0));
    assert_eq!(diagnostics.counters.session_opens, 2);
    assert_eq!(diagnostics.counters.session_closes, 1);
  }

  #[test]
  fn access_probe_accepts_an_optional_hold_but_hold_requires_probe() {
    assert!(
      Cli::try_parse_from(["mini-aec-sender", "--access-probe", "--hold-seconds", "5"]).is_ok()
    );
    assert!(Cli::try_parse_from(["mini-aec-sender", "--hold-seconds", "5"]).is_err());
  }
}
